export const business = {
  name: "SteelStud.ca",
  phone: "604-761-1518",
  phoneHref: "+16047611518",
  email: "frameinsteel@gmail.com",
  yearsSteel: 16,
  yearsContracting: 35,
};

export const services = [
  { slug: "framing-in-steel", name: "Steel Stud Framing", short: "Interior steel stud walls, bulkheads, backing and architectural assemblies built straight, strong and ready for finishing.", image: "service-steel.png", details: ["Commercial partitions and demising walls", "Condominium and strata renovations", "Bulkheads, soffits and ceiling features", "Backing, blocking and service coordination"] },
  { slug: "drywall", name: "Drywall Installation & Finishing", short: "Boarding, taping, finishing and repairs for renovations, offices, retail and multi-unit residential properties.", image: "service-drywall.png", details: ["Standard and fire-rated assemblies", "Level 4 and Level 5 finishing", "Patches and water-damage repairs", "Texture matching and smooth ceilings"] },
  { slug: "t-bar", name: "T-Bar & Suspended Ceilings", short: "Accessible acoustic ceiling systems for offices, retail, institutional and commercial interiors.", image: "service-tbar.png", details: ["Grid layout and installation", "Acoustic ceiling panels", "Lighting and mechanical coordination", "Repairs and tile replacement"] },
  { slug: "drop-ceilings", name: "Dropped Drywall Ceilings", short: "Custom framed ceiling drops and cloud features that create clean space for lighting, services and architectural detail.", image: "service-drop-ceilings.png", details: ["Recessed-lighting ceiling drops", "Cloud and tray ceilings", "Mechanical-service concealment", "Steel framing and drywall finish"] },
  { slug: "tenant-improvements", name: "Tenant Improvements", short: "Interior construction for offices, retail and mixed-use spaces, coordinated from framing through final finish.", image: "service-tenant-improvements.png", details: ["Office and retail partitions", "Ceilings and drywall", "Occupied-building coordination", "Deficiency and turnover work"] },
  { slug: "office-buildouts", name: "Office Buildouts", short: "Practical, durable office interiors for corporate, medical, technology and professional-service environments.", image: "service-tenant-improvements.png", details: ["Private offices and meeting rooms", "Reception and common areas", "Acoustic ceiling systems", "Phased and occupied renovations"] },
  { slug: "framing-in-wood", name: "Wood Framing", short: "Precise wood framing for interior renovations, backing, partitions and residential construction details.", image: "service-wood.png", details: ["Interior partitions", "Backing and blocking", "Renovation framing", "Ceiling and feature framing"] },
  { slug: "architectural-steel", name: "Architectural Steel", short: "Custom steel features and structural details coordinated with modern interior design.", image: "service-architectural-steel.png", details: ["Feature framing", "Custom supports", "Interior architectural details", "Trade coordination"] },
  { slug: "smoothing-ceilings", name: "Ceiling Smoothing", short: "Removal and refinishing of outdated textured ceilings for a clean, modern appearance.", image: "service-smoothing.png", details: ["Texture removal", "Surface preparation", "Skim coating", "Smooth final finish"] },
  { slug: "texture", name: "Wall & Ceiling Textures", short: "Professional texture application and matching for repairs, renovations and new construction.", image: "service-texture.png", details: ["Knockdown texture", "Orange peel", "Texture matching", "Repair blending"] },
  { slug: "repairs", name: "Drywall & Framing Repairs", short: "Careful repair of damaged drywall, framing and ceiling systems with clean integration into existing finishes.", image: "service-repairs.png", details: ["Water-damage repairs", "Drywall patches", "Framing corrections", "Ceiling repairs"] },
  { slug: "home-improvement", name: "Interior Home Improvements", short: "Interior renovation work backed by decades of general contracting and problem-solving experience.", image: "service-home-improvement.png", details: ["Condominium renovations", "Interior reconfiguration", "Ceiling upgrades", "Framing and drywall packages"] },
];

export const cities = [
  ["vancouver", "Vancouver", "Downtown towers, older West Side homes and East Vancouver mixed-use properties require careful access, noise and parking coordination."],
  ["burnaby", "Burnaby", "High-rise strata, Metrotown renovations and Brentwood commercial interiors benefit from organized deliveries and occupied-building planning."],
  ["new-westminster", "New Westminster", "Heritage buildings, compact sites and condominium renovations often demand custom ceiling and framing solutions."],
  ["richmond", "Richmond", "Retail, light-industrial and multi-unit projects require moisture-aware assemblies and dependable trade coordination."],
  ["surrey", "Surrey", "Growing commercial centres and multi-unit communities need scalable framing, drywall and ceiling crews."],
  ["delta", "Delta", "Industrial, commercial and residential interiors across North Delta, Ladner and Tsawwassen receive practical, site-specific planning."],
  ["white-rock", "White Rock", "Condominium and residential renovations require tidy work, careful access and respect for occupied buildings."],
  ["coquitlam", "Coquitlam", "High-rise development, retail and established residential properties create a broad mix of interior construction needs."],
  ["port-coquitlam", "Port Coquitlam", "Commercial units, industrial spaces and family homes receive durable framing and finish packages."],
  ["port-moody", "Port Moody", "Condominium growth and hillside homes call for precise interior assemblies and controlled logistics."],
  ["north-vancouver", "North Vancouver", "Sloped sites, high-value homes and strata buildings require careful planning, access and finish quality."],
  ["west-vancouver", "West Vancouver", "Custom residences and premium renovations demand exact tolerances, clean sites and immaculate finishes."],
  ["langley", "Langley", "Rapidly growing commercial, strata and residential areas need reliable crews across Langley City and Township."],
  ["maple-ridge", "Maple Ridge", "Residential growth and commercial interiors require flexible framing and drywall solutions."],
  ["pitt-meadows", "Pitt Meadows", "Commercial, agricultural and residential properties benefit from straightforward scheduling and durable assemblies."],
  ["abbotsford", "Abbotsford", "Fraser Valley commercial, multi-family and residential projects are supported with coordinated interior construction."],
].map(([slug,name,local]) => ({slug,name,local}));

export const projects = [
  { slug: "new-westminster-condo-dropped-ceiling", title: "New Westminster condominium dropped ceiling", image: "service-drop-ceilings.png", text: "A steel-stud and drywall ceiling drop created a clean cavity for recessed lighting and building services while preserving usable ceiling height.", challenge: "The renovation needed room for recessed lighting and services without making the condominium feel unnecessarily low or visually heavy.", approach: "A carefully laid-out light-gauge steel frame established a straight, stable ceiling plane. Openings and clearances were coordinated before board installation so the finished ceiling aligned with the lighting plan.", lesson: "Ceiling drops work best when framing, lighting layout and final drywall details are decided together—not handed from one trade to the next." },
  { slug: "custom-suspended-cloud-ceiling", title: "Custom suspended cloud ceiling", image: "hero-home-wide.png", text: "A suspended steel-stud framework formed a precise architectural ceiling feature, then received drywall and a smooth finish.", challenge: "A floating ceiling feature needs to look light and intentional while its concealed support remains rigid and accurately positioned.", approach: "The assembly was set out from finished reference lines, framed in steel and checked before drywall enclosed the structure. Edge proportions and the relationship to the surrounding ceiling controlled the visual result.", lesson: "Architectural ceiling features expose small layout errors. Early reference lines and repeated dimension checks protect the final geometry." },
  { slug: "commercial-tbar-acoustic-ceiling", title: "Suspended T-bar acoustic ceiling", image: "real-tbar-ceiling-example.jpg", text: "A serviceable acoustic grid ceiling provided clean access to lighting and mechanical systems for a commercial interior.", challenge: "The space required a clean finished ceiling while preserving practical access to electrical and mechanical services above.", approach: "The perimeter elevation, suspension points and grid were coordinated with fixtures and services. Acoustic panels completed an accessible, maintainable ceiling plane.", lesson: "T-bar performance depends on coordinated layout. Lighting, diffusers, sprinklers and access requirements should be resolved before the grid is finalized." },
];

export const guides = [
  { slug:"steel-stud-vs-wood-framing", title:"Steel Stud vs. Wood Framing for Interior Walls", image:"service-steel.png", intro:"Both systems can produce excellent interiors. The right choice depends on the building, wall height, services, moisture exposure, fire and acoustic requirements, available fastening points and the finish expected.", sections:[{"h":"Where steel studs perform well","p":"Steel framing is straight, dimensionally stable and well suited to commercial interiors, condominium renovations, tall partitions, bulkheads and assemblies that must coordinate closely with ceilings and services."},{"h":"Where wood framing remains useful","p":"Wood can be efficient for residential details, backing, short partitions and locations where conventional carpentry connections are practical. Existing construction often influences the best match."},{"h":"The decision is an assembly decision","p":"Stud material is only one part of the wall. Board layers, insulation, resilient components, backing, penetrations and perimeter details determine much of the finished performance."}], faqs:[["Is steel framing stronger than wood?","Strength depends on the complete design, member size, gauge, spacing, height, connections and intended load. The correct assembly should follow project requirements."],["Can steel studs be used in a condominium?","Yes. Steel studs are commonly useful for non-load-bearing interior partitions, drops and features, subject to the building rules and project design."],["Which system is better for sound control?","Acoustic performance comes from the complete wall assembly, not the stud material alone. Board layers, insulation, separation and sealed penetrations matter."]]},
  { slug:"tbar-vs-drywall-ceiling", title:"T-Bar Ceiling vs. Drywall Ceiling", image:"real-tbar-ceiling-example.jpg", intro:"The best ceiling is the one that balances appearance, access, acoustics, height and long-term maintenance for the actual space.", sections:[{"h":"Choose T-bar when access matters","p":"A suspended grid keeps services reachable and makes damaged panels replaceable. It is often practical for offices, retail, institutional and service-heavy commercial interiors."},{"h":"Choose drywall for a monolithic finish","p":"Drywall creates a continuous architectural surface and can form drops, clouds, coves and transitions. Access panels and service locations need to be planned deliberately."},{"h":"Coordinate before choosing","p":"Available ceiling height, lighting, ducts, sprinklers, structure and acoustic goals should be reviewed together. A reflected ceiling plan prevents trade conflicts."}], faqs:[["Is a T-bar ceiling cheaper than drywall?","Cost depends on the grid, panel, ceiling height, room geometry, access and service coordination. Compare complete installed systems rather than material prices alone."],["Which ceiling is better for offices?","T-bar is often preferred where services need ongoing access; drywall may suit reception areas, executive spaces and architectural features."],["Can both systems be combined?","Yes. Drywall borders or clouds are often combined with accessible acoustic-grid fields."]]},
  { slug:"condo-renovation-framing-guide", title:"Condo & Strata Interior Framing Guide", image:"service-home-improvement.png", intro:"Condominium work is construction inside an operating community. Access, approvals, noise, elevators, protection and cleanup must be planned alongside the framing and drywall.", sections:[{"h":"Start with building requirements","p":"Confirm permitted hours, elevator bookings, loading access, protection standards, debris handling and any strata approval process before scheduling material deliveries."},{"h":"Verify existing conditions","p":"Walls, ceilings and floors are rarely perfectly square. Service locations and concrete structure may differ from assumptions, so field measurement should guide layout."},{"h":"Protect the occupied building","p":"Dust control, corridor protection, controlled cutting and daily cleanup are part of the work—not optional extras."}], faqs:[["Do strata renovations need approval?","Requirements vary by corporation and scope. Owners should review bylaws and obtain required approvals before construction."],["Can steel studs be used for condo ceiling drops?","Yes, when the assembly and attachment are appropriate for the project. Steel is useful for straight, stable bulkheads and ceiling features."],["How should noise be managed?","Plan noisy work within approved hours, communicate the schedule and use appropriate cutting and dust-control methods."]]},
  { slug:"tenant-improvement-construction-sequence", title:"Tenant Improvement Construction Sequence", image:"service-tenant-improvements.png", intro:"A successful tenant improvement is a coordinated sequence. Decisions made before framing protect the schedule when mechanical, electrical, ceilings and finishes arrive.", sections:[{"h":"1. Existing conditions and layout","p":"Confirm dimensions, building services, base-building restrictions and the approved plan. Mark partitions and review clearances before ordering or cutting."},{"h":"2. Framing, backing and rough-ins","p":"Frame partitions and ceiling features, then coordinate backing and service penetrations. Inspection requirements should be built into the schedule."},{"h":"3. Board, ceilings and finish","p":"Close assemblies only after required reviews. Drywall finish levels, ceiling grids, doors and final fixtures then proceed in a controlled order."}], faqs:[["What causes tenant-improvement delays?","Unresolved layouts, late service changes, missing approvals and poor trade sequencing are common causes."],["When should backing be installed?","Before walls are closed, based on millwork, displays, washroom accessories, televisions and other mounted items."],["Can work happen in an occupied building?","Often yes, with approved hours, protection, dust control, access planning and communication."]]},
  { slug:"drywall-finish-levels-explained", title:"Drywall Finish Levels Explained", image:"service-drywall.png", intro:"The correct drywall finish depends on lighting, paint sheen, surface visibility and the final decoration. Higher numbers do not automatically mean every wall needs the highest level.", sections:[{"h":"Typical painted interiors","p":"Level 4 is commonly specified for flat or low-sheen painted surfaces under ordinary lighting, subject to the design and specification."},{"h":"Critical light and premium surfaces","p":"Level 5 adds a skim treatment intended to reduce visible differences across board and joint areas. It may be considered for strong side-lighting or more demanding finishes."},{"h":"Quality begins before taping","p":"Framing alignment, board orientation, fastener setting, joint placement and environmental conditions all affect the final surface."}], faqs:[["Does Level 5 guarantee a perfect wall?","No finish eliminates every effect of extreme lighting or substrate movement. Expectations, lighting and paint should be reviewed together."],["What level is needed behind tile?","The required substrate depends on the tile system and wet-area design. Follow the project specification and product requirements."],["Can old texture be made smooth?","Often yes, after checking adhesion, damage, coatings and the condition of the existing surface."]]},
  { slug:"sound-isolation-condo-walls", title:"Sound Isolation for Condo Interior Walls", image:"service-steel.png", intro:"Quiet walls come from complete assemblies and careful details. A single acoustic product cannot compensate for open gaps, rigid shortcuts or untreated penetrations.", sections:[{"h":"Mass, absorption and separation","p":"Additional board layers add mass, cavity insulation absorbs energy and resilient separation can reduce direct vibration paths. The design must consider the whole wall."},{"h":"Flanking paths matter","p":"Sound can travel through ceilings, floors, ducts, outlets and adjoining assemblies. Perimeters and penetrations require the same attention as the main wall surface."},{"h":"Coordinate specialist requirements","p":"Where measurable acoustic performance is required, use an assembly selected or reviewed for the project. For broader acoustic systems and finishes, see Acustiq.ca."}], faqs:[["Do steel studs help sound isolation?","They can be part of effective acoustic assemblies, but performance depends on the full tested or designed wall system."],["Does insulation soundproof a wall?","Insulation helps absorb cavity energy but does not by itself soundproof a wall."],["Should electrical boxes line up back-to-back?","Back-to-back penetrations can weaken acoustic separation. Their locations and treatment should be coordinated."]], related:"https://acustiq.ca"},
  { slug:"planning-fire-rated-interior-assemblies", title:"Planning Fire-Rated Interior Assemblies", image:"service-drywall.png", intro:"Fire-rated walls and ceilings are systems. Studs, board type and layers, fasteners, joints, head details, penetrations and continuity must match the required design.", sections:[{"h":"Identify the required assembly","p":"The drawings and specifications should identify the applicable rating and assembly. Do not substitute components based only on appearance."},{"h":"Coordinate penetrations early","p":"Electrical, mechanical and plumbing penetrations can affect continuity. Their locations and required protection should be resolved before closure."},{"h":"Document before board hides the work","p":"Photos and inspection checkpoints help confirm backing, framing, services and continuity before assemblies are enclosed."}], faqs:[["Is fire-rated drywall enough to make a rated wall?","No. Rating applies to a complete assembly built to the applicable design, not to one product by itself."],["Can a rated wall stop at a suspended ceiling?","That depends on the required design and construction documents. Some separations must continue to structure."],["Who confirms the required rating?","The project drawings, specifications and responsible design or code professionals should establish the requirement."]]},
  { slug:"ceiling-smoothing-or-replacement", title:"Smooth an Existing Ceiling or Replace It?", image:"service-smoothing.png", intro:"The right approach depends on adhesion, damage, previous coatings, ceiling flatness, service access and the finish expected under the room’s lighting.", sections:[{"h":"When smoothing may work","p":"A stable, well-adhered surface can often be prepared and skimmed. Test areas help reveal coating or adhesion problems before full production."},{"h":"When replacement may be cleaner","p":"Extensive damage, loose texture, major irregularity or required service changes can make selective removal or new board more predictable."},{"h":"Lighting reveals the result","p":"Large windows and low-angle fixtures exaggerate surface variation. Finish expectations and lighting should be discussed before choosing the process."}], faqs:[["Can every textured ceiling be smoothed?","No. Existing materials, coatings, damage and adhesion need assessment first."],["Is smoothing dust-free?","Surface work creates dust, but containment, extraction and controlled sanding reduce migration."],["Will a smooth ceiling show more defects?","Strong side-lighting can reveal small variations, so preparation and finish level matter."]]}
];
